# Generated by Django 3.2.9 on 2021-11-23 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deptname',
            fields=[
                ('dept_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.dept')),
                ('it', models.BooleanField(default=False, max_length=30)),
                ('electrical', models.BooleanField(default=False, max_length=30)),
                ('mechanical', models.BooleanField(default=False, max_length=30)),
            ],
            bases=('app1.dept',),
        ),
        migrations.RemoveField(
            model_name='dept',
            name='deptname',
        ),
    ]
